export const MUTSUKI_KAVITA_VERSION = "0.1.12";
export const MUTSUKI_KAVITA_SHORT_SHA = "progress-boundary";
export const MUTSUKI_KAVITA_BUILD = `${MUTSUKI_KAVITA_VERSION}+${MUTSUKI_KAVITA_SHORT_SHA}`;
